---
name: unit

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
        ruby: ['3.1', '3.4']
    name: Unit test on ${{ matrix.os }} with Ruby ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    env:
      RUBYOPT: '--disable-error_highlight'
    steps:
      - uses: actions/checkout@v4
      - name: ruby-setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake spec